let wordList = [
    { word: "grammar", hint: "rules for writing and speaking correctly" },
    { word: "adverb", hint: "a word that describes a verb" },
    { word: "vocabulary", hint: "collection of known words" },
    { word: "sentence", hint: "a group of words forming a complete thought" },
    { word: "noun", hint: "a person, place, or thing" },
    { word: "verb", hint: "an action word" },
    { word: "prefix", hint: "a word part added at the beginning" },
    { word: "suffix", hint: "a word part added at the end" },
    { word: "punctuation", hint: "symbols like . , ! used in writing" },
    { word: "essay", hint: "a short piece of writing on a topic" },
    { word: "synonym", hint: "a word that means the same" },
    { word: "antonym", hint: "a word that means the opposite" },
    { word: "idiom", hint: "a phrase with a hidden meaning" },
    { word: "paragraph", hint: "a block of sentences around one idea" },
    { word: "metaphor", hint: "comparison without using 'like' or 'as'" },
    { word: "simile", hint: "comparison using 'like' or 'as'" },
    { word: "article", hint: "words like 'a', 'an', and 'the'" },
    { word: "pronoun", hint: "replaces a noun (like he, she, it)" },
    { word: "capital", hint: "uppercase letter" },
    { word: "dictionary", hint: "book of word meanings" },
    { word: "question", hint: "a sentence that asks something" },
    { word: "answer", hint: "a reply to a question" },
    { word: "alphabet", hint: "a to z collection" },
    { word: "letter", hint: "a single character like A or B" },
    { word: "editing", hint: "correcting and improving text" },
    { word: "spelling", hint: "correct order of letters in a word" },
    { word: "story", hint: "a narrative of events" },
    { word: "chapter", hint: "a section of a book" },
    { word: "title", hint: "the name of a book or story" },
    { word: "author", hint: "person who writes a book" },
    { word: "poem", hint: "a piece of writing with rhythm" },
    { word: "past", hint: "something that already happened" },
    { word: "future", hint: "something yet to happen" },
    { word: "edit", hint: "to change or correct writing" },
    { word: "publish", hint: "to make writing public" },
    { word: "library", hint: "place full of books" },
    { word: "read", hint: "to look at and understand words" },
    { word: "write", hint: "to create words on paper" },
    { word: "learn", hint: "to gain knowledge" },
    { word: "knowledge", hint: "information or skills gained" },
    { word: "education", hint: "the process of learning" },
    { word: "school", hint: "place where learning happens" },
    { word: "teacher", hint: "someone who teaches" },
    { word: "student", hint: "someone who learns" },
    { word: "paper", hint: "material for writing or printing" },
    { word: "pen", hint: "tool for writing with ink" },
    { word: "eraser", hint: "removes pencil writing" },
    { word: "language", hint: "system of communication" },
    { word: "accent", hint: "way of speaking a language" }
];
